services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    develop:
      context: .
      dockerfile: ./docker/backend.dev.Dockerfile
      watch:
        - action: sync
          path: ./apps/backend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    develop:
      context: .
      dockerfile: ./docker/frontend.dev.Dockerfile
      watch:
        - action: sync
          path: ./apps/frontend
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: package.json
    ports:
      - '3001:3001'
    depends_on:
      - backend

volumes:
  db-data:
